name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for SkillService
      uses: docker/build-push-action@v2
      with:
        context: ./SkillService
        file: ./SkillService/Dockerfile
        push: true
        tags: javad0098/skillservice:latest

    - name: Build and push Docker image for CertificateService
      uses: docker/build-push-action@v2
      with:
        context: ./CertificateService
        file: ./CertificateService/Dockerfile
        push: true
        tags: javad0098/certificateservice:latest
